### ISSUE TITLE
Strange pathfinding

### ISSUE THREAD

**Issue by JoeCooper** [OsmSharp/OsmSharp#208] opened 2015-01-21 10:18 UTC
I'm using the latest from git for both execution and the conversion from xml to the contracted hierarchies routing file. I got something like this:

![screen shot 2015-01-21 at 11 15 06 am](https://cloud.githubusercontent.com/assets/5166338/5834546/214def4c-a15f-11e4-88cb-982a8a096eee.png)

The source data (xml) has been used before successfully.

WDYT?

**Comment by xivk** [comment] 2015-01-21 10:55
Ok that's not looking very good... I just noticed some test have been failing that checks this stuff.

These are fixed now. Sorry about this, this kind of regression is caught by the unittests, but I overlooked the fact that they failed.

**Comment by JoeCooper** [comment] 2015-01-21 11:44
I've pulled the new changes, rebuilt the router file and ran it again (making sure to clean and rebuild everything with newest sources) but it doesn't seem to have solved the problem.

**Comment by xivk** [comment] 2015-01-21 11:56
Can you send me a code sample and if possible the area of routing and/or the serialized file?

You can get in touch with me via this form:

http://www.osmsharp.com/contact#overlay-context=contact

I will reply with my private email.

**Comment by xivk** [comment] 2015-01-26 10:42
In some cases the shapes of an edge are not copied correctly. Fixed this now... It slipped by the tests because it only occurs in middle to larger networks. 

Will close this issue after I have test coverage on the piece of code causing the issue. 

I'm updating the odp-tool and things will be back to normal.

**Comment by JoeCooper** [comment] 2015-01-26 10:43
> In some cases the shapes of an edge are not copied correctly. Fixed this now... It slipped by the tests because it only occurs in middle to larger networks.
> 
Thanks a lot.
> Will close this issue after I have test coverage on the piece of code causing the issue.
> 
I’ll try it shortly.

– Joe=

**Comment by xivk** [comment] 2015-01-26 10:56
One more problem in de odp-tool. Checking now...

**Comment by xivk** [comment] 2015-01-26 11:48
I updated everything, tested the entire workflow again. The route you suggested is now calculated correctly:

http://geojson.io/#id=gist:anonymous/2cad6a8e4429816ff7c3&map=14/46.9110/-102.7882

Let me know if you have more problems...

**Comment by JoeCooper** [comment] 2015-01-27 15:12
You’re right. It’s working. Thanks a lot.

– Joe

**Closed** 2015-02-12 09:15 UTC
Labels: bug, planned
