### ISSUE TITLE
Bounding Box not working properly

### ISSUE THREAD

**Issue by erkinyldz** [OsmSharp/OsmSharp#202] opened 2015-01-03 13:52 UTC
var from = new GeoCoordinate (41.0017, 29.0381);
var to = new GeoCoordinate (40.9781, 29.0145);
var box = new GeoCoordinateBox (from, to);
_mapView.MapBoundingBox = box;

This bounding box not working properly. It gets stuck everytime I scroll it to very left and don't let you scroll anymore. If you want the code here is the github link:
https://github.com/erkinyldz/KadikoyMap

**Comment by xivk** [comment] 2015-05-25 17:37
Duplicate of #55

**Closed by xivk** 2015-05-25 17:37 UTC
Labels: bug, ui
